name: Lint Code

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Ajuste la version PHP si nécessaire

      - name: Install dependencies
        run: |
          make install

      - name: Run PHP Lint
        run: |
          make lint
